# Generated by Django 3.1.7 on 2021-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210503_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phnumber', models.CharField(max_length=100)),
                ('checkin', models.DateTimeField(max_length=100)),
                ('checkout', models.DateTimeField(max_length=100)),
                ('roomtype', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'room_book',
            },
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
