# Generated by Django 3.1.7 on 2021-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210505_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('verification', models.CharField(max_length=100)),
                ('phnumber', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'cancel_book',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateTimeField(max_length=20),
        ),
    ]
