# Generated by Django 3.1.7 on 2021-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210512_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateTimeField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateTimeField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phnumber',
            field=models.IntegerField(max_length=100),
        ),
    ]
